meta_product_name: "Gégé"
meta_title: "Gégé - l'assistant qui gère tes réservations clients"
meta_description: "Gérez vos réservations, sans changer vos habitudes. Gégé vous fait gagner du temps et des clients !"
meta_image: "cover.jpg"
